#sudo: required

language: java
script:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && mvn -B deploy --settings .travis-settings.xml || mvn -B verify --settings .travis-settings.xml'
jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk10
